// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yghrfxxfvuqasvldjdzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnaHJmeHhmdnVxYXN2bGRqZHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MjE2MDUsImV4cCI6MjA1NTA5NzYwNX0.jJHJg7nkdTT7-RV5X6FKz8Ub67ov7wNUnPksyb7P1dY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);